version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: quimicenter
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quimicenter_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/quimicenter
    ports:
      - "3030:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: quimicenter
      DATABASE_PASSWORD: password
      DATABASE_NAME: quimicenter_development

volumes:
  postgres_data: