default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'quimicenter_production') %>

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  database: quimicenter_test

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] || 'quimicenter_production' %>
